Examples/LaunchKey.Examples.AspMvc/Models/AccountModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Globalization;
using System.Web.Mvc;
using System.Web.Security;

namespace LaunchKey.Examples.AspMvc.Models
{
	public class LoginModel
	{
		public string LaunchKeyUserName { get; set; }
		public int ErrorCode { get; set; }
		public string ErrorMessage { get; set; }
	}


	public class LoginNewUserModel
	{
		[HiddenInput]
		public string AuthRequest { get; set; }

		[StringLength(30)]
		[Required]
		[Display(Name = "Hi! What should we call you?")]
		public string FriendlyName { get; set; }
	}
}

Examples/LaunchKey.Examples.AspMvc/Models/TreasureChestModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LaunchKey.Examples.AspMvc.Models
{
	public class TreasureChestModel
	{
		public int XpGained { get; set; }
		public string ItemGained { get; set; }
	}
}

Examples/LaunchKey.Examples.AspMvc/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using LaunchKey.Examples.AspMvc.Models;
using LaunchKey.SDK.Rest;
using System.Configuration;
using LaunchKey.Examples.AspMvc.LaunchKey;

namespace LaunchKey.Examples.AspMvc.Controllers
{
	[Authorize]
	public class AccountController : Controller
	{
		[AllowAnonymous]
		[NoCache]
		public ActionResult LoginJson(string username)
		{
			var lkClient = LaunchKeyClientFactory.GetInstanceFromConfig();
			var authsResponse = lkClient.Authenticate(username, AuthenticationType.Session);
			return Json(authsResponse, JsonRequestBehavior.AllowGet);
		}

		[AllowAnonymous]
		[NoCache]
		public ActionResult LoginPollJson(string authRequest)
		{
			var lkClient = LaunchKeyClientFactory.GetInstanceFromConfig();
			var pollResponse = lkClient.Poll(authRequest);
			
			// request failed for some reason, let client error out
			if (!pollResponse.Successful)
			{
				return Json(new { Successful = false, Waiting = false, ErrorCode = pollResponse.MessageCode, ErrorMessage = pollResponse.Message }, JsonRequestBehavior.AllowGet);
			}

			// request succeeded but still waiting
			if (pollResponse.UserHash == null)
			{
				return Json(new { Successful = true, Waiting = true }, JsonRequestBehavior.AllowGet);
			}

			// request succeeded, device responded with an OK
			if (pollResponse.DecryptedAuth.Response)
			{
				return Json(new { Successful = true, Waiting = false, Accepted = true, RedirectUrl = Url.Action("LoginConfirm", new { authRequest = authRequest }) }, JsonRequestBehavior.AllowGet);
			}
			// request succeeded, device rejected
			else
			{
				lkClient.Logs(LogsAction.Authenticate, LogsStatus.Denied, authRequest);
				return Json(new { Successful = true, Waiting = false, Accepted = false }, JsonRequestBehavior.AllowGet);
			}

		}


		[AllowAnonymous]
		public ActionResult Login(string returnUrl)
		{
			ViewBag.ReturnUrl = returnUrl;
			return View();
		}

		[AllowAnonymous]
		public ActionResult LoginConfirm(string authRequest)
		{
			// confirm successful request.
			// Check hash against user database
			// If hash exists, login to that user 
			// If hash not exists, redirect to confirm details view

			var lkClient = LaunchKeyClientFactory.GetInstanceFromConfig();

			// verify authenticity of auth request
			var pollResponse = lkClient.Poll(authRequest);

			if (lkClient.IsAuthorized(authRequest, pollResponse))
			{
				var db = new LkExampleDatabaseDataContext();

				// auth success, let's check if we know this person
				var currentUser = db.Users.Where(u => u.LaunchKeyUserHash == pollResponse.UserHash).FirstOrDefault();

				// we do, so set their auth cookie and send them back to the home page
				if (currentUser != null)
				{
					currentUser.LastAuthRequest = authRequest;
					db.SubmitChanges();
					this.SetAuthCookie(currentUser);
					return RedirectToAction("Index", "Home");
				}
				// unknown user. serve them the new user form
				else
				{
					return View("LoginNewUser", new LoginNewUserModel { AuthRequest = authRequest });
				}
			}
			else
			{
				// show login error, send back to Login()
				return View("Login", new { Error = true, ErrorMessage = pollResponse.Message });
			}
		}

		[AllowAnonymous]
		[HttpPost]
		public ActionResult LoginNewUser(LoginNewUserModel model)
		{
			if (ModelState.IsValid)
			{
				var lkClient = LaunchKeyClientFactory.GetInstanceFromConfig();
				var pollResponse = lkClient.Poll(model.AuthRequest);

				if (!lkClient.IsAuthorized(model.AuthRequest, pollResponse))
				{
					ModelState.AddModelError(string.Empty, string.Format("Error communicating with LaunchKey. Response code: {0}, message: {1}", pollResponse.MessageCode, pollResponse.MessageCode));
					return View();
				}

				// create new user and login 
				var db = new LkExampleDatabaseDataContext();
				var newUser = new User { FirstName = model.FriendlyName, LastAuthRequest = model.AuthRequest, LaunchKeyUserHash = pollResponse.UserHash };
				db.Users.InsertOnSubmit(newUser);
				db.SubmitChanges();

				this.SetAuthCookie(newUser);
				return RedirectToAction("Index", "Home");
			}
			else
			{
				return View();
			}
		}
		
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult LogOff()
		{
			// logout locally
			FormsAuthentication.SignOut();

			var lkIdentity = User != null ? User.Identity as LaunchKeyIdentity : null;
			if (lkIdentity != null)
			{
				// notify launchKey
				var lkClient = LaunchKeyClientFactory.GetInstanceFromConfig();
				lkClient.Logout(lkIdentity.AuthRequest);
			}

			return RedirectToAction("Index", "Home");
		}


		private void SetAuthCookie(User user)
		{
			FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(
				2,
				user.LaunchKeyUserHash,
				DateTime.Now,
				DateTime.Now.AddMinutes(15),
				false,
				string.Format("{0};;{1}", user.LastAuthRequest, user.FirstName)
			);
			string encryptedTicket = FormsAuthentication.Encrypt(ticket);
			HttpCookie cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
			cookie.Expires = DateTime.Now.AddMinutes(15);
			Response.Cookies.Add(cookie);
		}


	}
}

Examples/LaunchKey.Examples.AspMvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LaunchKey.Examples.AspMvc.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}
	}
}

Examples/LaunchKey.Examples.AspMvc/Controllers/TreasureChestController.cs
using LaunchKey.Examples.AspMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LaunchKey.Examples.AspMvc.Controllers
{
    public class TreasureChestController : Controller
    {
		static string[] Loot = {
			"a Goblin Poking Sword of Awesomeness",
			"an Ancient Essence of Overweight Ogres",
			"a Fleeting Bow of the Anxious Elf"
							   };
		[NoCache]
        public ActionResult Index()
        {
			var r = new Random();
			return View(new TreasureChestModel { ItemGained = Loot[r.Next() % Loot.Length], XpGained = r.Next(30, 90) });
        }

    }
}

Examples/LaunchKey.Examples.AspMvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "LaunchKey";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title!</h1>
            </hgroup>
            <p>
                This demo application includes hidden treasures ... 
            </p>
        </div>
    </section>
}

<h3>ASP.NET MVC Direct LaunchKey Integration Example</h3>
<p>This demo application shows what a direct API implementation of LaunchKey's authentication API might look like.</p>
<p>Try logging in!</p>

Examples/LaunchKey.Examples.AspMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @RenderSection("styles", required: false)
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("LaunchKey MVC Example", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            @if (WebSecurity.IsAuthenticated) {
                                <li>@Html.ActionLink("Treasures", "Index", "TreasureChest")</li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - LaunchKey MVC Example</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
        
    </body>
</html>

Examples/LaunchKey.Examples.AspMvc/Views/TreasureChest/Index.cshtml
@model LaunchKey.Examples.AspMvc.Models.TreasureChestModel

@{
    ViewBag.Title = "Treasure";
}

<h2>Treasure</h2>
<div style="text-align: center">
    <h3>You found my treasure. <br />You gained <span style="color: darkgoldenrod">@Model.XpGained XP</span>!<br /> ... and found <span style="color: cadetblue">@Model.ItemGained</span>!</h3>
    <p><img src="~/Content/treasure.png" /></p>
    
</div>